# permissions for end users to edit vessels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vessel-editor-role
rules:
- apiGroups:
  - cache.sourcesense
  resources:
  - vessels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.sourcesense
  resources:
  - vessels/status
  verbs:
  - get
