# permissions for end users to view vessels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vessel-viewer-role
rules:
- apiGroups:
  - cache.sourcesense
  resources:
  - vessels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.sourcesense
  resources:
  - vessels/status
  verbs:
  - get
